//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLog
    {
        public long access_id { get; set; }
        public string access_username { get; set; }
        public string access_ip { get; set; }
        public Nullable<System.DateTime> access_date { get; set; }
        public Nullable<int> access_success { get; set; }
    }
}
