//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int cliente_id { get; set; }
        public string cliente_codigo { get; set; }
        public string cliente_nombre { get; set; }
        public string cliente_RFC { get; set; }
        public string cliente_direccion_calle { get; set; }
        public string cliente_direccion_numeroInterior { get; set; }
        public string cliente_direccion_numeroExterior { get; set; }
        public string cliente_direccion_pais { get; set; }
        public string cliente_direccion_estado { get; set; }
        public string cliente_direccion_ciudad { get; set; }
        public string cliente_direccion_colonia { get; set; }
        public Nullable<int> cliente_status { get; set; }
        public Nullable<decimal> cliente_saldo { get; set; }
        public string cliente_interno { get; set; }
        public string cliente_puedefacturar { get; set; }
    }
}
