//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DFLPOS_DISTRIBUTION
    {
        public int id { get; set; }
        public Nullable<int> version_id { get; set; }
        public Nullable<int> site_id { get; set; }
        public string estate { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
    
        public virtual DFLPOS_SITES DFLPOS_SITES { get; set; }
        public virtual DFLPOS_VERSIONS DFLPOS_VERSIONS { get; set; }
    }
}
