//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DFLPOS_VERSIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DFLPOS_VERSIONS()
        {
            this.DFLPOS_DISTRIBUTION = new HashSet<DFLPOS_DISTRIBUTION>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string version { get; set; }
        public string files { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DFLPOS_DISTRIBUTION> DFLPOS_DISTRIBUTION { get; set; }
    }
}
