//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DFLPOS_SITES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DFLPOS_SITES()
        {
            this.DFLPOS_DISTRIBUTION = new HashSet<DFLPOS_DISTRIBUTION>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string ip { get; set; }
        public string ftp_user { get; set; }
        public string ftp_password { get; set; }
        public string destination_route { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DFLPOS_DISTRIBUTION> DFLPOS_DISTRIBUTION { get; set; }
    }
}
