//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DFLPOS_UPDATEREntities : DbContext
    {
        public DFLPOS_UPDATEREntities()
            : base("name=DFLPOS_UPDATEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<HistorialDistribucion> HistorialDistribucion { get; set; }
        public virtual DbSet<PosVersionFiles> PosVersionFiles { get; set; }
        public virtual DbSet<PosVersions> PosVersions { get; set; }
        public virtual DbSet<SiteHealthChecks> SiteHealthChecks { get; set; }
        public virtual DbSet<Sucursales> Sucursales { get; set; }
        public virtual DbSet<SYS_LOG> SYS_LOG { get; set; }
        public virtual DbSet<SYS_PAGE_MASTER> SYS_PAGE_MASTER { get; set; }
        public virtual DbSet<SYS_ROLE_MASTER> SYS_ROLE_MASTER { get; set; }
        public virtual DbSet<SYS_ROLE_PAGE> SYS_ROLE_PAGE { get; set; }
        public virtual DbSet<SYS_ROLE_USER> SYS_ROLE_USER { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UpdateJobs> UpdateJobs { get; set; }
        public virtual DbSet<UpdateJobTargets> UpdateJobTargets { get; set; }
        public virtual DbSet<UpdateLogs> UpdateLogs { get; set; }
        public virtual DbSet<USER_LOGGING> USER_LOGGING { get; set; }
        public virtual DbSet<USER_MASTER> USER_MASTER { get; set; }
        public virtual DbSet<USER_PWD> USER_PWD { get; set; }
        public virtual DbSet<VersionPos> VersionPos { get; set; }
        public virtual DbSet<AggregatedCounter> AggregatedCounter { get; set; }
        public virtual DbSet<Counter> Counter { get; set; }
        public virtual DbSet<Hash> Hash { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<JobParameter> JobParameter { get; set; }
        public virtual DbSet<JobQueue> JobQueue { get; set; }
        public virtual DbSet<List> List { get; set; }
        public virtual DbSet<Schema> Schema { get; set; }
        public virtual DbSet<Server> Server { get; set; }
        public virtual DbSet<Set> Set { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<SitesConfig> SitesConfig { get; set; }
        public virtual DbSet<SYS_LOG_CONNECTION> SYS_LOG_CONNECTION { get; set; }
        public virtual DbSet<SITE_CONFIG> SITE_CONFIG { get; set; }
        public virtual DbSet<DFLPOS_DISTRIBUTION> DFLPOS_DISTRIBUTION { get; set; }
        public virtual DbSet<DFLPOS_SITES> DFLPOS_SITES { get; set; }
        public virtual DbSet<DFLPOS_VERSIONS> DFLPOS_VERSIONS { get; set; }
    }
}
