//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialDistribucion
    {
        public int Id { get; set; }
        public string Sucursal { get; set; }
        public string Version { get; set; }
        public System.DateTime FechaEnvio { get; set; }
        public bool Exitoso { get; set; }
        public string Resultado { get; set; }
    }
}
