//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int menu_id { get; set; }
        public string menu_nombre { get; set; }
        public string menu_descripcion { get; set; }
        public string menu_url { get; set; }
        public string menu_imagen { get; set; }
        public Nullable<int> menu_orden { get; set; }
        public Nullable<int> menu_padre { get; set; }
        public Nullable<bool> menu_habilitado { get; set; }
    }
}
