//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GiftCardEntities1 : DbContext
    {
        public GiftCardEntities1()
            : base("name=GiftCardEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PackagesDetail> PackagesDetails { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TarjetaPackagesDetail> TarjetaPackagesDetails { get; set; }
        public virtual DbSet<Tarjeta> Tarjetas { get; set; }
        public virtual DbSet<TarjetaTransfer> TarjetaTransfers { get; set; }
        public virtual DbSet<AccessLog> AccessLogs { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Historial> Historials { get; set; }
        public virtual DbSet<HistorialTipo> HistorialTipoes { get; set; }
        public virtual DbSet<MailLog> MailLogs { get; set; }
        public virtual DbSet<MailMaster> MailMasters { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<PaqueteVenta> PaqueteVentas { get; set; }
        public virtual DbSet<PaqueteVentaDetalle> PaqueteVentaDetalles { get; set; }
        public virtual DbSet<Perfile> Perfiles { get; set; }
        public virtual DbSet<PerfilesDetail> PerfilesDetails { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<TARJETA_CARGA_MASIVA_TEMP> TARJETA_CARGA_MASIVA_TEMP { get; set; }
        public virtual DbSet<TarjetaDescuento> TarjetaDescuentos { get; set; }
        public virtual DbSet<TarjetaPackage> TarjetaPackages { get; set; }
        public virtual DbSet<TarjetasSaldoAnterior> TarjetasSaldoAnteriors { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
