//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosVersionFiles
    {
        public int Id { get; set; }
        public int VersionId { get; set; }
        public string FileName { get; set; }
        public long FileSizeBytes { get; set; }
        public byte[] FileHashSha256 { get; set; }
        public string StoragePath { get; set; }
        public bool IsRequired { get; set; }
    
        public virtual PosVersions PosVersions { get; set; }
    }
}
