//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITES
    {
        public string site_code { get; set; }
        public string site_name { get; set; }
        public string site_type { get; set; }
        public string ip_address { get; set; }
        public string port { get; set; }
        public string address { get; set; }
        public string postal_code { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string email_manager { get; set; }
        public string phone { get; set; }
        public string acc_store_id { get; set; }
        public string district_code { get; set; }
        public Nullable<bool> delete_flag { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public string cuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public string uuser { get; set; }
        public string site_connection_string { get; set; }
        public string site_serie { get; set; }
        public bool new_erp { get; set; }
        public Nullable<System.DateTime> new_erp_date { get; set; }
        public string host_name { get; set; }
    }
}
