//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteHealthChecks
    {
        public long Id { get; set; }
        public int SiteId { get; set; }
        public System.DateTime CheckedAt { get; set; }
        public string RemotePath { get; set; }
        public string FileName { get; set; }
        public bool ExistsFlag { get; set; }
        public string Notes { get; set; }
    }
}
