//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitesConfig
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FtpHost { get; set; }
        public string FtpUser { get; set; }
        public string FtpPassEnc { get; set; }
        public string DestPath { get; set; }
        public bool Active { get; set; }
    }
}
