//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITE_CONFIG
    {
        public string site_code { get; set; }
        public string site_name { get; set; }
        public string site_irs_name { get; set; }
        public string site_rfc { get; set; }
        public string tax_regime { get; set; }
        public string site_state { get; set; }
        public string site_city { get; set; }
        public string site_address { get; set; }
        public string site_zipcode { get; set; }
        public string site_user_server { get; set; }
        public string site_user_pwd { get; set; }
        public byte[] desk_app_con { get; set; }
        public byte[] movil_app_con { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public string cuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public string uuser { get; set; }
        public string program_id { get; set; }
    }
}
