//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PAGE_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_PAGE_MASTER()
        {
            this.SYS_ROLE_PAGE = new HashSet<SYS_ROLE_PAGE>();
        }
    
        public string page_id { get; set; }
        public string page_name { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public Nullable<bool> active_flag { get; set; }
        public string level_1_menu { get; set; }
        public string level_2_menu { get; set; }
        public string level_3_menu { get; set; }
        public string type { get; set; }
        public Nullable<int> menu_sequence { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public string cuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public string uuser { get; set; }
        public string program_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_ROLE_PAGE> SYS_ROLE_PAGE { get; set; }
    }
}
