//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_LOG_CONNECTION
    {
        public int conn_code { get; set; }
        public string emp_no { get; set; }
        public Nullable<System.DateTime> connlog_date { get; set; }
        public Nullable<System.DateTime> connlogout_date { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public Nullable<bool> conn_status { get; set; }
    }
}
