//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_LOG
    {
        public long id { get; set; }
        public string TableName { get; set; }
        public string idAfect { get; set; }
        public string Action { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
        public string uuser { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string time { get; set; }
        public string Menu { get; set; }
        public Nullable<System.DateTime> Cdate { get; set; }
        public Nullable<int> Type { get; set; }
        public string Program_id { get; set; }
    }
}
