//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public int tarjeta_id { get; set; }
        public string tarjeta_numero { get; set; }
        public Nullable<decimal> tarjeta_monto { get; set; }
        public string tarjeta_referencia { get; set; }
        public Nullable<int> cliente_id { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> tarjeta_tipo { get; set; }
        public string tarjeta_dv { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public bool registro_nuevo { get; set; }
        public string ActivationID { get; set; }
    }
}
