//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARJETA_CARGA_MASIVA_TEMP
    {
        public int tarjeta_id { get; set; }
        public string no_empleado { get; set; }
        public string nombre { get; set; }
        public decimal monto { get; set; }
        public System.DateTime timestamp { get; set; }
        public string Sucursal { get; set; }
        public string No_Tarjeta { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> partner_id { get; set; }
    }
}
