//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateJobTargets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UpdateJobTargets()
        {
            this.UpdateLogs = new HashSet<UpdateLogs>();
        }
    
        public long Id { get; set; }
        public int JobId { get; set; }
        public int SiteId { get; set; }
        public string TargetPath { get; set; }
        public string FtpHost { get; set; }
        public string FtpUser { get; set; }
        public byte[] FtpPassEnc { get; set; }
        public bool Active { get; set; }
        public byte Status { get; set; }
        public string LastMessage { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public Nullable<System.DateTime> EndedAt { get; set; }
        public string BackupPath { get; set; }
        public string RemoteVersion { get; set; }
    
        public virtual UpdateJobs UpdateJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UpdateLogs> UpdateLogs { get; set; }
    }
}
