//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateLogs
    {
        public long Id { get; set; }
        public long TargetId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public byte Level { get; set; }
        public string Message { get; set; }
    
        public virtual UpdateJobTargets UpdateJobTargets { get; set; }
    }
}
