//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PWD
    {
        public string emp_no { get; set; }
        public Nullable<System.DateTime> valid_from { get; set; }
        public Nullable<System.DateTime> valid_to { get; set; }
        public Nullable<int> failed_attempts { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> last_logon { get; set; }
        public string last_logon_ip { get; set; }
        public Nullable<System.DateTime> last_pwd_change { get; set; }
        public string password { get; set; }
        public string pass_code { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public string cuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
    
        public virtual USER_MASTER USER_MASTER { get; set; }
    }
}
