//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_LOGGING
    {
        public System.DateTime logdate { get; set; }
        public string page_id { get; set; }
        public string emp_no { get; set; }
        public string ip_address { get; set; }
        public string command { get; set; }
        public string remark { get; set; }
    }
}
