<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dflpos-updater-web-dev</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\Content\Images\Empresa\logoflorido.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DflPosUpdater.App.Entities\DflPosUpdater.App.Entities.csproj" />
    <ProjectReference Include="..\DflPosUpdater.App.DAL\DflPosUpdater.App.DAL.csproj" />
    <ProjectReference Include="..\DflPosUpdater.App.BLL\DflPosUpdater.App.BLL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BuildBundlerMinifier" Version="3.2.449" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.23" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.5.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
